"""
qbr2.py — QBR Generator 2.0.

Produces client-ready Quarterly Business Reviews with:
- Executive summary with health score
- Activity timeline
- Key decisions made
- Lessons learned
- Opportunities identified
- Expansion recommendations
"""

import datetime
import json
from typing import Dict, List, Optional, Any
from grid_memory.local_grid import LocalGrid
from grid_memory.engagement import EngagementGraph
from grid_memory.product.expansion import ExpansionScore


class QBRGenerator2:
    """Generates polished Quarterly Business Reviews.

    Args:
        grid: LocalGrid instance for a client
        client: Client identifier
    """

    def __init__(self, grid: LocalGrid, client: str = ""):
        self.grid = grid
        self.client = client
        self.engagement = EngagementGraph(grid)

    def generate(self, quarter: str = "") -> Dict:
        """Generate a complete QBR with all sections.

        Args:
            quarter: Quarter label (e.g. "Q2 2026")

        Returns:
            Dict with full QBR ready for rendering
        """
        if not quarter:
            q = (datetime.datetime.now(datetime.timezone.utc).month - 1) // 3 + 1
            quarter = f"Q{q} {datetime.datetime.now(datetime.timezone.utc).year}"

        qbr = self.engagement.generate_qbr(self.client, quarter)
        expansion = ExpansionScore(self.grid, self.client).calculate()

        # Executive summary
        qbr["executive_summary"] = self._executive_summary(qbr, expansion)
        qbr["expansion"] = expansion
        qbr["health"] = self._health_score(qbr)

        return qbr

    def format_clients(self) -> str:
        """Format QBR as client-ready markdown text."""
        qbr = self.generate()
        lines = [
            f"# Quarterly Business Review",
            f"**Client:** {self.client}",
            f"**Period:** {qbr.get('quarter', 'Current')}",
            f"**Generated:** {qbr.get('generated_at', '')[:10]}",
            f"",
            f"## Executive Summary",
            f"",
            f"**Health Score:** {qbr.get('health', {}).get('score', 0)}/100 — {qbr.get('health', {}).get('level', 'N/A')}",
            f"**Activities:** {qbr.get('summary', {}).get('total_activities', 0)}",
            f"**Lessons:** {qbr.get('summary', {}).get('lessons_learned', 0)}",
            f"**Opportunities:** {qbr.get('summary', {}).get('opportunities_identified', 0)}",
            f"**Expansion Score:** {qbr.get('expansion', {}).get('overall_score', 0)}/100",
            f"",
            f"## Key Decisions",
            f"",
        ]
        for d in qbr.get("decisions", [])[:5]:
            lines.append(f"- {d.get('content', '')[:100]}")
        lines.append("")
        lines.append("## Lessons Learned")
        lines.append("")
        for l in qbr.get("lessons", [])[:5]:
            lines.append(f"- {l.get('content', '')[:100]}")
        lines.append("")
        lines.append("## Opportunities Identified")
        lines.append("")
        for o in qbr.get("opportunities", [])[:5]:
            stage = o.get("stage", "detected")
            lines.append(f"- [{stage}] {o.get('content', '')[:100]}")
        lines.append("")
        lines.append("## Expansion Recommendation")
        lines.append("")
        lines.append(qbr.get("expansion", {}).get("recommendation", "N/A"))
        lines.append("")
        lines.append("---")
        lines.append(f"*Generated by Grid Memory — Operational Intelligence Graph*")

        return "\n".join(lines)

    def _executive_summary(self, qbr: Dict, expansion: Dict) -> str:
        return (
            f"During {qbr.get('quarter', 'this period')}, "
            f"{qbr.get('summary', {}).get('total_activities', 0)} activities were tracked "
            f"across {qbr.get('summary', {}).get('phases_active', 0)} engagement phases. "
            f"{qbr.get('summary', {}).get('lessons_learned', 0)} lessons were captured and "
            f"{qbr.get('summary', {}).get('opportunities_identified', 0)} opportunities identified. "
            f"Expansion score: {expansion.get('overall_score', 0)}/100."
        )

    def _health_score(self, qbr: Dict) -> Dict:
        """Calculate a composite health score from QBR data."""
        s = qbr.get("summary", {})
        score = 50  # baseline
        if s.get("total_activities", 0) > 5: score += 10
        if s.get("total_activities", 0) > 20: score += 10
        if s.get("lessons_learned", 0) > 3: score += 10
        if s.get("opportunities_identified", 0) > 2: score += 10
        if s.get("phases_active", 0) > 2: score += 10
        score = min(score, 100)
        level = "Excellent" if score >= 80 else ("Good" if score >= 60 else ("Fair" if score >= 40 else "Needs Attention"))
        return {"score": score, "level": level}
